version: "3"
services:
  # node_proxy:
  #   build: ./Proxy
  #   ports:
  #     - 4000:8080
  #   environment:
  #     - SERVER_PORT=8080
  #     - BOOKS_SERVICE=http://books:8080
  #     - AUTHORS_SERVICE=http://authors:8080
  #   links:
  #     - "books_service"
  #     - "authors_service"

  # books_service:
  #   build: ./BooksService
  #   ports:
  #     - 4001:8080
  #   environment:
  #     - SERVER_PORT=8080
  #     - MONGO_URL=mongodb://books_mongo:27017/library
  #   links:
  #     - "books_mongo"

  # books_mongo:
  #   image: mongo
  #   volumes:
  #     - ./BooksService/data:/data/db
  #   ports:
  #     - 4002:27017

  # authors_service:
  #   build: ./AuthorsService
  #   ports:
  #     - 4003:8080
  #   environment:
  #     - SERVER_PORT=8080
  #     - MONGO_URL=mongodb://authors_mongo:27017/library
  #   links:
  #     - "authors_mongo"

  # authors_mongo:
  #   image: mongo
  #   volumes:
  #     - ./AuthorsService/data:/data/db
  #   ports:
  #     - 4004:27017

  mydb:
    image: postgres
    volumes:
      - ./UsersService/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - 5000:5432
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pwdpwd
    volumes:
      - ./UsersService/pgadmin:/root/.pgadmin
    ports:
      - 5001:80
