version: "2"
services:
  books_service:
    container_name: books_service
    restart: always
    build: ./BooksService
    ports:
      - "4001:8080"
    environment:
      - SERVER_PORT=8080
      - MONGO_URL=mongodb://mongo:27017/library
    links:
      - "books_mongo:mongo"

  books_mongo:
    container_name: books_mongo
    image: mongo
    volumes:
      - ./BooksService/data:/data/db
    ports:
      - "4002:27017"

  authors_service:
    container_name: authors_service
    restart: always
    build: ./AuthorsService
    ports:
      - "4003:8080"
    environment:
      - SERVER_PORT=8080
      - MONGO_URL=mongodb://authors_mongo:27017/library
    links:
      - "authors_mongo:mongo"

  authors_mongo:
    container_name: authors_mongo
    image: mongo
    volumes:
      - ./AuthorsService/data:/data/db
    ports:
      - "4004:27017"